services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'      #Idealmente, deveria-se usar váriaveis de ambiente para maior segurança
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
